# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  GODOT_VERSION: 3.2.3
  EXPORT_NAME: opensuspect

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  export:
    name: Export
    runs-on: ubuntu-latest
    container:
      image: monban/godot-ci:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          chown -R root:root /github/home
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
          mv /root/rcedit.exe $GITHUB_WORKSPACE/
      - name: Linux Build
        run: |
          mkdir -v -p $GITHUB_WORKSPACE/build/linux
          cd $GITHUB_WORKSPACE/src
          godot -v --export "Client" $GITHUB_WORKSPACE/build/linux/$EXPORT_NAME.x86_64
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: build/linux
      - name: Windows Desktop Build
        run: |
          mkdir -v -p $GITHUB_WORKSPACE/build/windows-desktop
          cd $GITHUB_WORKSPACE/src
          godot -v --export "Windows Desktop" $GITHUB_WORKSPACE/build/windows-desktop/$EXPORT_NAME.exe
      - name: Convert png to ico
        run: convert $GITHUB_WORKSPACE/src/assets/common/textures/icons/icon.png -define icon:auto-resize="256,128,96,64,48,32,16" ~/icon.ico
      - name: Change exe icon
        run: cd $GITHUB_WORKSPACE; wine $GITHUB_WORKSPACE/rcedit.exe $GITHUB_WORKSPACE/build/windows-desktop/$EXPORT_NAME.exe --set-icon ~/icon.ico
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows-desktop
          path: build/windows-desktop
